ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000
ARG NVIM_VERSION=v0.12.4
ARG LAZYGIT_VERSION=0.64.1
ARG UV_VERSION=0.12.5
ARG DEV_TOOLS_PYTHON=3.12

ENV DEBIAN_FRONTEND=noninteractive \
    EDITOR=nvim \
    VISUAL=nvim \
    TERM=xterm-256color \
    UV_PYTHON_INSTALL_DIR=/opt/uv/python \
    PATH=/opt/dev-tools/bin:/usr/local/bin:$PATH

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY install/ /tmp/dev-env/install/
RUN NVIM_VERSION="$NVIM_VERSION" \
    LAZYGIT_VERSION="$LAZYGIT_VERSION" \
    UV_VERSION="$UV_VERSION" \
    DEV_TOOLS_PYTHON="$DEV_TOOLS_PYTHON" \
    /tmp/dev-env/install/install-ide.sh && \
    /tmp/dev-env/install/create-user.sh "$USERNAME" "$USER_UID" "$USER_GID" && \
    rm -rf /tmp/dev-env/install

COPY --chown=${USER_UID}:${USER_GID} dotfiles/nvim/ /home/${USERNAME}/.config/nvim/
COPY --chown=${USER_UID}:${USER_GID} dotfiles/yazi/ /home/${USERNAME}/.config/yazi/
COPY --chown=${USER_UID}:${USER_GID} dotfiles/tmux/tmux.conf /home/${USERNAME}/.tmux.conf
COPY --chown=${USER_UID}:${USER_GID} dotfiles/bash/bashrc /home/${USERNAME}/.bashrc

USER ${USERNAME}
WORKDIR /workspaces
CMD ["sleep", "infinity"]
