# dev-env shell additions. Sourced from ~/.bashrc by bootstrap.sh.

case $- in
  *i*) ;;
  *) return ;;
esac

export PATH="$HOME/.local/bin:$PATH"
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export LESS='-R'

alias ll='ls -alF'
alias la='ls -A'
alias gs='git status -sb'
alias gd='git diff'
alias gl='git log --oneline --decorate --graph -20'
alias v='nvim'
alias lg='lazygit'

# Yazi wrapper: when Yazi exits, follow its final directory in the current shell.
y() {
  local tmp cwd
  tmp="$(mktemp -t yazi-cwd.XXXXXX)"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [[ -n "$cwd" && "$cwd" != "$PWD" ]]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}
